### ISSUE TITLE
ground truth bgs

### ISSUE THREAD

**Issue by TheMasterRoot** [cioppaanthony/rt-sbs#1]
hello could you provide me any example in python of how to do ground truth bgs using two frames?

**Comment by cioppaanthony** [comment]
Hi,
Unfortunately, I did not understand your query. Could you please elaborate ? 
Thanks

**Comment by ldenoue** [comment]
by the way, will the source code be released, and if so, when approximately?
Thanks!
Laurent

**Comment by cioppaanthony** [comment]
Thanks for your interest ! Yes, the code will be released, approximately in September I would say.
Actually, we will present the paper at the ICIP2020 conference in October. We'll also have a video explaining the method on our YouTube Channel: [Acad AI Research](https://www.youtube.com/channel/UCYkYA7OwnM07Cx78iZ6RHig), but it will probably be posted at the same time as the conference (so a bit later than the code).

**Comment by TheMasterRoot** [comment]
i dont know how to make a background substration using ground thruth
could you give me any example in python?

**Comment by cioppaanthony** [comment]
The code is now released. I am very sorry for the delay... 
I hope that it will run smoothly. Don't hesitate to provide feedbacks otherwise ! :-)
