### ISSUE TITLE
Multiprocessing problem

### ISSUE THREAD

**Issue by WeiXiaoSummer** [cioppaanthony/rt-sbs#3]
Hi! What an amazing work! I am trying to implement your method with other bg algorithms but I have a problem, how did you run the vibe and PSPNet concurrently? I was trying with the torch.multiprocessing but seems like it's not the best method, could you tell me how did you implement this part please? Thanks in advance!

**Comment by cioppaanthony** [comment]
Hi,

Thanks for your interest!

I would suggest that you take a look at how the multiprocessing was implemented in one of my other project that needs to run in real-time as well: https://github.com/cioppaanthony/online-distillation. 

In this repo, it is Mask-RCNN (teacher) and a TinyNet (the student) that run in parallel on different devices with different frame rates as well. To implement the real-time code, I used the multiprocessing python library and queues to transfer the data between the different threads. It might not be the most optimized way to do so, but it does the job.

I hope this helps!

**Comment by Rm1n90** [comment]
Hey @cioppaanthony, 

I have the same problem in parallelizing the Vibe and PSPNet with multiprocessing! Can you please share the code for the multiprocessing part or provide more information on how I'm able to do it?  

Also, I have a question about ViBe, when did you transfer the vibe from GPU to CPU? did you calculate everything with ViBeGPU and transfer the final mask to the CPU?

Thanks!
