### ISSUE TITLE
this  work for dynamic background ???

### ISSUE THREAD

**Issue by SabraHashemi** [cioppaanthony/rt-sbs#4]
hi 
i dont idea about your code so i have a question
this sbs workes when background is moving also?
for example a factory rail is as background and objects are like  box ?

**Comment by cioppaanthony** [comment]
Hi,

I'm not sure I fully understand your setup. Is the camera moving or is there just moving objects in the background ?

In the first cas, this method would not be that good if the camera is moving.
You could try to improve it. To do so, you need to make at least two adjustments. 
1. You should use a background subtraction algorithm that handles moving cameras, which is not the case of ViBe, that we use.
2. The change detection algorithm also has to be able to handle moving cameras.

In the second case, so if their are moving objects in the background, then yes, you could use our method and simply remove from the semantic segmentation all moving objects that you want in the background. You then, just need to select, for semantic segmentation, the objects that you're interested in in the foreground.

I hope this helps

**Comment by SabraHashemi** [comment]
Hi
Thanks for reply,
i mean something like
objects on a convey belt , bet is not all black  
so belt is moving and objects are on it

**Comment by cioppaanthony** [comment]
Yes, it should work since the semantic segmentation will classify the convey belt as background.

But then for the change detection algorithm, maybe a more sophisticated model could improve further the performance, for instance if the change detection algorithm can "retain" several colors rather than just one as we did.
