### ISSUE TITLE
ViBeGPU for one channel image 

### ISSUE THREAD

**Issue by batman47steam** [cioppaanthony/rt-sbs#7]
Hi, cioppaanthony
I wonder whether the ViBeGPU code is  suitable for one channel gray image, it seems that in `update_` there is only `if` statement for three channel image, and not for the one channel case, but I think the code wrapped by `if` statement is also suitable for one channel image ?
![image](https://user-images.githubusercontent.com/36287035/195011972-dd292521-2323-43b1-b447-56dfcbfbf98d.png)
thanks again for this wonderful studying

**Comment by cioppaanthony** [comment]
Hi @batman47steam,

Thank you for your nice comment. :-)

Indeed, the provided code was only meant for RGB channels, but it can be easily adapted for grayscale I think. 
Note that one very simple way is to transform the grayscale image  to a 3-channel image by repeating the channel dimension. 
However it would be more efficient to only use one channel in the calculations.

It could be that the code right now is agnostic on the number of channels, but I'm not 100% sure. 
For instance, there may be issues in other parts of the code. 
Could you please try and let me know if you have an error somewhere?

Thanks in advance.

**Comment by batman47steam** [comment]
Thanks for the answering, I will give it a try
